### ISSUE TITLE
Mongo DB migrations failing using Djongo

### ISSUE THREAD

**Issue by foo290** [fabiocaccamo/django-admin-interface#137]
**Python version**
3.8.10

**Django version**
3.2.8

**Package version**
0.17.3

**Current behavior (bug description)**
migration failing in mongo db, also Im using `Djongo` to integrate with mongo db

**Expected behavior**
Should have migrated sucessfully

**Here is the stack trace:**
```
Running migrations:
  Applying admin_interface.0020_module_selected_colors...This version of djongo does not support "schema validation using NOT NULL" fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "COLUMN DROP DEFAULT " fully. Visit https://nesdis.github.io/djongo/support/
Traceback (most recent call last):
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/cursor.py", line 51, in execute
    self.result = Query(
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 784, in __init__
    self._query = self.parse()
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 876, in parse
    raise e
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 857, in parse
    return handler(self, statement)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 918, in _update
    query = UpdateQuery(self.db, self.connection_properties, sm, self._params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 297, in __init__
    super().__init__(*args)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 62, in __init__
    self.parse()
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 324, in parse
    self.kwargs.update(self.set_columns.to_mongo())
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/converters.py", line 303, in to_mongo
    '$set': {
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/converters.py", line 305, in <dictcomp>
    if sql.rhs_indexes is not None else None
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/sql2mongo/sql_tokens.py", line 195, in rhs_indexes
    raise SQLDecodeError
djongo.exceptions.SQLDecodeError: 

        Keyword: None
        Sub SQL: None
        FAILED SQL: ('UPDATE "admin_interface_theme" SET "css_module_link_selected_color" = "admin_interface_theme"."css_module_link_color"',)
        Params: ((),)
        Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/admin_interface/migrations/0020_module_selected_colors.py", line 14, in default_link_selected
    Theme.objects.using(db_alias).update(
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/models/query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/linuxpanda/workstation/github/Python/Inventory/venv/lib/python3.8/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
```

**Comment by fabiocaccamo** [comment]
@foo290 feel free to add mongo db to the test suite.

**Comment by fabiocaccamo** [comment]
@foo290 this seems to be more a `Djongo` issue.
