### ISSUE TITLE
migrate fails at "change_related_modal_background_opacity_type"

### ISSUE THREAD

**Issue by acegallagher** [fabiocaccamo/django-admin-interface#52]
Hi there. Thanks for the great interface. I'm trying to migrate from a function setup with Python 3.6, Django 2.1.5, and admin-interface 0.9.1 . When I run migrate on my development computer I end up with the following traceback. I'm happy to help debug but the process of debugging if I can. 

`  Applying admin_interface.0008_change_related_modal_background_opacity_type...Traceback (most recent call last):
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 663, in _alter_field
    params,
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is in recovery mode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 108, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/transaction.py", line 256, in __exit__
    connection.set_autocommit(True)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 394, in set_autocommit
    self.ensure_connection()
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ace/.local/share/virtualenvs/website-10j77PrM/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is in recovery `mode``

**Comment by fabiocaccamo** [comment]
@acegallagher I think it is a postgres related issue.
Could you try to test it with another db?

**Comment by Tberdy** [comment]
Hi, I got an old project using Django 2.0.7 and django-admin-interface 0.5.9.
After updating it to Django 2.1.5 and django-admin-interface 0.9.1, the same migration begin to fail to fail during pytest db creation and during migrate (when creating new db).
I'm using Posgresql 11.1.

**Comment by fabiocaccamo** [comment]
@acegallagher @Tberdy I released a `0.9.2` version and added postgres to tox and travis, could you test it?

If the problem persists, could you write a test case which fails?

**Comment by apecnascimento** [comment]
I have the same error with django 2.1.7 and django-admin-interface 0.9.2.

**Comment by fabiocaccamo** [comment]
@apecnascimento could you retry after renaming the migration with a shorter name?

**Comment by fabiocaccamo** [comment]
@merwok have you any idea about what is happening here?

**Comment by fabiocaccamo** [comment]
I think that a test against migrations should be written, here a useful post about migrations testing: 
https://www.caktusgroup.com/blog/2016/02/02/writing-unit-tests-django-migrations/

**Comment by merwok** [comment]
The first problem is this:
> psycopg2.OperationalError: server closed the connection unexpectedly

Do you have postgresql logs to see what causes this?

**Comment by fabiocaccamo** [comment]
@acegallagher, @Tberdy, @apecnascimento if you don't partecipate actively, the issue will be closed in the next days.

**Comment by pooyamb** [comment]
I was trying to test admin-interface, and the exact error happened to me, did you find any solution for this?
I tried with fresh startproject with same result, and I can confirm it has nothing to do with migration name.but If I remove migrations folder and do makemigrations, migrate works.
here is the log from postgres:
2019-05-06 22:28:48.650 +0430 [12780] LOG:  database system is ready to accept connections
2019-05-06 22:28:56.179 +0430 [12780] LOG:  server process (PID 10480) was terminated by exception 0xC0000005
2019-05-06 22:28:56.179 +0430 [12780] DETAIL:  Failed process was running: ALTER TABLE "admin_interface_theme" ALTER COLUMN "related_modal_background_opacity" TYPE varchar(5) USING "related_modal_background_opacity"::varchar(5)
2019-05-06 22:28:56.179 +0430 [12780] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-05-06 22:28:56.180 +0430 [12780] LOG:  terminating any other active server processes

**Comment by merwok** [comment]
Searching for the exception code indicates hardware problem.

**Comment by pooyamb** [comment]
Yes I saw that mailing list too, but I don't think that could be the case,
I think the problem comes from altering double precision to varchar, I tested the query directly in postgres and the result was same,
So it has nothing to do with this app in particular but removing the field and adding it again in migration can solve the problem.

**Comment by fabiocaccamo** [comment]
@pooyamb could you fix migrations and send a PR?

**Comment by pooyamb** [comment]
@fabiocaccamo I sent a PR

**Comment by fabiocaccamo** [comment]
@pooyamb thank you, I think this problem should be reported to the django project.

**Comment by fabiocaccamo** [comment]
@pooyamb you can install `0.10.5` version.
